platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Example' do
 config = use_native_modules!
 use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # Pods for Example
#  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

#   use_native_modules!
end

target 'Example-tvOS' do
  # Pods for Example-tvOS

  target 'Example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
